image: ruby:2.4

services:
  - postgres:latest

variables:
  POSTGRES_DB: crowdfunding_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  RAILS_ENV: test

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs postgresql
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - cp config/database.yml.gitlab config/database.yml
  - bundle exec rails db:drop db:create db:migrate

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

rspec:
  script:
    - bundle exec rspec
