version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node-browsers

        environment:
          RAILS_ENV: test

    working_directory: ~/crowdfunder

    steps:
      - checkout

      - run: gem install bundler

      # Setup the environment
      - run: cp config/database.yml.example config/database.yml

      # Bundle with caching strategy
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake
