default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV['CI'].blank? ? "localhost" : "postgres" %>
  username: <%= ENV['CI'].blank? ? "postgres" : "runner" %>
  password:
  database: crowdfunding_test

production:
  <<: *default
  database: db/production.sqlite3
